### ISSUE TITLE
星の仕様がわからへん

### ISSUE THREAD

**Issue by dev-platong** [CA21engineer/RealtimeQuiz#16]
# こうしたい

1. 待機ルームでは，星の数と前回の星との増減値を表示する

<img width="307" alt="スクリーンショット 2020-07-12 23 03 22" src="https://user-images.githubusercontent.com/33997070/87248616-5dbc1580-c495-11ea-95d2-6657ae75b7de.png">

例：　⭐️8 （＋1）

2. 回答の評価中には星を表示しない

右上の星をなくす

理由：　忖度してると回答に星つけるのに時間かかりすぎる説

<img width="582" alt="スクリーンショット 2020-07-12 23 11 26" src="https://user-images.githubusercontent.com/33997070/87248588-336a5800-c495-11ea-93db-a93a649b1b3b.png">

**Comment by kqito** [comment]
こちら実装したのでcloseしますね！
