### ISSUE TITLE
名前変更の型ミス

### ISSUE THREAD

**Issue by BambooTuna** [CA21engineer/RealtimeQuiz#31]
- 現状
<img width="239" alt="スクリーンショット 2020-07-14 23 47 04" src="https://user-images.githubusercontent.com/39406526/87439988-61ce6b80-c62c-11ea-8a77-b35f50dac7c3.png">

- 仕様

```
{
    'type': 'ChangeName',
​
    'data': {
        'accountName': string
    }
}
```

### やること
- typeの先頭は大文字
- data型を直す

**Comment by kqito** [comment]
対応済みなのでclose!!
