### ISSUE TITLE
フロントの初期をVanilla JSのみで開発するにあたって確認したいこと

### ISSUE THREAD

**Issue by dev-platong** [CA21engineer/RealtimeQuiz#4]
# こうしたい

- 動くのは正義だがstrict modeは欲しい
- 基本的な考え方として，HTMLをベタがきしてJSでのDOM操作は値を流し込むだけ
- 明らかにコンポーネント化した方が良いものが出てきたらHTMLで頑張らず、尚且つPureJSにこだわらない

例えば汎用的に使い回したいbuttonに

```javascript
  // @param {String} mountTargetStr
  function generateGeneralButton(mountTargetStr){
    const mountTarget = document.getElementById(mountTarget);
    const buttonElement = document.createElement("button");
    buttonElement.addEventListener("click" ...

    mountTarget.appendChild(buttonElement);
  }
```

みたいなコードが必要になったら多分ReactかVue突っ込んだ方が早いと思う

- いけるタイミングでTS化する

## 上記のすべての意見にこだわりないです

ソフトウェアは動くことが正義だと思うので，それ以外の全てを一緒に開発してくれている人たちに合わせたいと考えて生きてます．TSよりJSの方がスピード開発できる人も多いので，その全てを皆さんに合わせます:teishisei:

**Comment by kqito** [comment]
> 動くのは正義だがstrict modeは欲しい
> 基本的な考え方として，HTMLをベタがきしてJSでのDOM操作は値を流し込むだけ

自分もこの認識！

> 例えば汎用的に使い回したいbuttonに ~ ReactかVue突っ込んだ方が早いと思う

これは本当にそう思う。何かを汎用的に使い回すコンポーネントが多く出るならフレームワーク + tsしたい。個人的にはreact派。

個人的な意見だけど、僕は静的型付けじゃないと不安で夜しか寝れない人間です。でも自分も強いこだわりはないので周りに合わせます！

そもそも今回Vanillaでやったのは @kznrluk のキャッチアップのコストとかを踏まえて納期に間に合わせる為だと聞いたので、イベント後はフレームワークにリファクタするという流れを取りたいと思っていたりします。

**Comment by kqito** [comment]
React + ts 導入したのでヨシ！
